Finish News System Implementation
rocky-linux/rockylinux.org pull request #5
Opened 2024-02-18 20:15 UTC by ressonix

2024-02-18 23:58 UTC, NebraskaCoder requested changes
Check my comments to see if the comment and the share buttons need improvement. If not, let me know and I can approve the PR.

2024-02-18 23:58 UTC, NebraskaCoder commented on app/[locale]/news/page.tsx
> +import { format } from "date-fns"; // Assuming you have a date formatting library
Did you mean to leave this comment?

2024-02-18 23:58 UTC, NebraskaCoder commented on components/shareButtons/ShareButtons.tsx
Is this file dedicated for news slugs? If so, let's locate these components to be in a components folder in the app folder (app/[locale]/news/components) instead of the global components. If not, we should take a prop for the type of slug ('news', 'somethingElse', 'etc...') and generate the URL based on that.

2024-02-19 01:06 UTC, ressonix commented on components/shareButtons/ShareButtons.tsx
I'll correct this, I meant to make these re-usable anywhere. Thanks for noticing that.

2024-02-19 01:07 UTC, ressonix commented on app/[locale]/news/page.tsx
> +import { format } from "date-fns"; // Assuming you have a date formatting library
LOL no. Will correct this.

2024-02-19 12:46 UTC, NebraskaCoder approved these changes

2024-02-19 12:46 UTC, merged